spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Automatically updates schema
    show-sql: true # Prints SQL queries in logs
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8082 # Account microservice runs on port 8081